version: 2

updates:
  - package-ecosystem: "npm"
    open-pull-requests-limit: 1
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "fix(ci): "
      prefix-development: "fix(ci): "
    reviewers:
      - superflyxxi
  - package-ecosystem: "npm"
    open-pull-requests-limit: 1
    directory: "/zine-generator"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "fix(zine-generator): "
      prefix-development: "fix(deps-dev): "
    reviewers:
      - superflyxxi
  - package-ecosystem: "docker"
    open-pull-requests-limit: 1
    directory: "/zine-generator"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "fix(zine-generator): "
      prefix-development: "fix(deps-dev): "
    reviewers:
      - superflyxxi
  - package-ecosystem: "npm"
    open-pull-requests-limit: 1
    directory: "/common"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "fix(common): "
      prefix-development: "fix(deps-dev): "
    reviewers:
      - superflyxxi
  - package-ecosystem: "docker"
    open-pull-requests-limit: 1
    directory: "/common"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "fix(common): "
      prefix-development: "fix(deps-dev): "
    reviewers:
      - superflyxxi
  - package-ecosystem: "npm"
    directory: "/posts"
    open-pull-requests-limit: 1
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "fix(posts): "
      prefix-development: "fix(deps-dev): "
    reviewers:
      - superflyxxi
  - package-ecosystem: "docker"
    directory: "/posts"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "fix(posts): "
      prefix-development: "fix(deps-dev): "
    reviewers:
      - superflyxxi
  - package-ecosystem: "npm"
    directory: "/template"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "fix(template): "
      prefix-development: "fix(deps-dev): "
    reviewers:
      - superflyxxi
  - package-ecosystem: "docker"
    directory: "/template"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "fix(template): "
      prefix-development: "fix(deps-dev): "
    reviewers:
      - superflyxxi
  - package-ecosystem: "npm"
    directory: "/int-test"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "test: "
      prefix-development: "test: "
    reviewers:
      - superflyxxi
  - package-ecosystem: "docker"
    directory: "/int-test"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "test: "
      prefix-development: "test: "
    reviewers:
      - superflyxxi
