openapi: 3.0.3
info:
  title: Social Zine
  description: Social Zine RESTful APIs
  version: 0.0.0


components:
  schemas:
    Post:
      type: object
      properties:
        socialNetwork:
          type: string
          description: The social network identifier.
          example: fb
        content:
          type: string
          description: The content of the post.
  parameters:
    social-zine-user-id:
      name: SZ-User-Id
      in: header
      example: 12389343
      description: The Social Zine User ID
      required: true
      schema:
        type: string

paths:
  /posts:
    get:
      parameters:
        - $ref: '#/components/parameters/social-zine-user-id'
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Post'
