openapi: 3.0.3
info:
  title: Social Zine
  description: Social Zine RESTful APIs
  version: 0.0.0

components:
  schemas:
    Post:
      type: object
      required:
        - socialNetwork
        - content
        - originator
      properties:
        _id:
          type: string
          description: The Post identifier.
          example: 37947398
        socialNetwork:
          type: string
          description: The social network identifier.
          example: fb
        content:
          type: string
          description: The content of the post.
          example: This is the first post I ever created.
        originator:
          type: string
          description: The ID of the originator of the post.
          example: 123897493
        reactions:
          type: array
          description: The likes for this Post.
          items:
            $ref: '#/components/schemas/Reaction'
    Reaction:
      type: object
      required:
        - originator
      properties:
        originator:
          type: string
          description: The ID of the originator of the Reaction.
          example: 17893893
        type:
          enum:
            - like
          description: The type of Reaction
  
  parameters:
    social-zine-user-id:
      name: SZ-User-Id
      in: header
      example: 12389343
      description: The Social Zine User ID
      required: true
      schema:
        type: string

paths:
  /posts:
    get:
      parameters:
        - $ref: '#/components/parameters/social-zine-user-id'
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Post'
